@echo off

setlocal
set BASE_VERSION_MAJOR=0
set BASE_VERSION_MINOR=5
set HEADER_FILE=%~dp0%\include\version.h

setlocal EnableDelayedExpansion

set GENERATE_OUTPUT=true
if "%1"=="-print" (
	set GENERATE_OUTPUT=false
) else (
    echo Generating version info file...
)

set defaultBuildNumber=0

set VER_BUILD=%BUILD_NUMBER%
if "!VER_BUILD!"=="" set VER_BUILD=%defaultBuildNumber%

set cmd="git rev-list --first-parent --count HEAD -- %VERSION_DIRECTORY%"
FOR /F "tokens=*" %%i IN (' %cmd% ') DO SET REVISION=%%i

set cmd="git log --max-count=1 --pretty=%%H -- %VERSION_DIRECTORY%"
FOR /F "tokens=*" %%i IN (' %cmd% ') DO SET HASH=%%i

if "%HASH%"=="" (
    set HASH32=0
) else (
    set HASH32=%HASH:~0,-32%
)

if %GENERATE_OUTPUT%==false goto PRINT_VERSION

if not exist %~dp0\include (mkdir %~dp0\include)

(
    echo #pragma once
    echo.
    echo // Autogenerated using update-version.bat do not modify
    echo #define VERSION_MAJOR %BASE_VERSION_MAJOR%
    echo #define VERSION_MINOR %BASE_VERSION_MINOR%
    echo #define VERSION_REVISION %REVISION%
    echo #define VERSION_BUILD %VER_BUILD%
    echo #define VERSION_COMMIT_HASH "%HASH32%";
    echo #define VERSION_COMMIT_HASH_FULL "%HASH%";
    echo #define VERSION_DATE "%DATE%"
    echo #define VERSION_PROJECT %BASE_VERSION_MAJOR%,%BASE_VERSION_MINOR%,%REVISION%,%VER_BUILD%
    echo #define VERSION_PROJECT_STR "%BASE_VERSION_MAJOR%.%BASE_VERSION_MINOR%.%REVISION%.%VER_BUILD%-%HASH32%"

)> %HEADER_FILE%

:PRINT_VERSION
echo %BASE_VERSION_MAJOR%.%BASE_VERSION_MINOR%.%REVISION%.%VER_BUILD%-%HASH32%

endlocal
